name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild all artifacts'
        required: false
        default: false
        type: boolean

# Prevent concurrent deployments
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  R2_PUBLIC_URL: https://pub-4e99d31d19cb404d8d4f5f7efa51ef6e.r2.dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      contents: write
      pages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            processor/.venv
            ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ hashFiles('processor/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      
      - name: Cache PDFs
        uses: actions/cache@v3
        with:
          path: content/pdfs/**/*.pdf
          key: ${{ runner.os }}-pdfs-${{ hashFiles('content/pdfs/**/*.md') }}
          restore-keys: |
            ${{ runner.os }}-pdfs-
      
      # CRITICAL FIX: Use a stable cache key for the build cache file
      # This allows the build system to track what has already been processed
      - name: Cache build state
        uses: actions/cache@v3
        with:
          path: processor/.build_cache.json
          # Use a stable key that doesn't change with file contents
          key: ${{ runner.os }}-build-cache-v2
          # Always restore the most recent cache
          restore-keys: |
            ${{ runner.os }}-build-cache-v2
            ${{ runner.os }}-build-cache-
      
      # Cache generated artifacts separately with content-based keys
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            processor/artifacts/
            frontend/public/artifacts/
          # This key changes when content changes, but doesn't affect build cache
          key: ${{ runner.os }}-artifacts-${{ hashFiles('content/pdfs/**/*.md') }}-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-artifacts-${{ hashFiles('content/pdfs/**/*.md') }}-
            ${{ runner.os }}-artifacts-
      
      - name: Setup Python environment
        working-directory: processor
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          pip install --upgrade "natural-pdf[all] @ git+https://github.com/jsoma/natural-pdf.git"
          pip install easyocr
          pip install doclayout_yolo
          pip install "surya-ocr<0.15"
          
      - name: Download missing PDFs
        working-directory: processor
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          pip install boto3
          python scripts/download_pdfs_from_r2_sync.py
      
      # SIMPLIFIED: Let the build system decide what needs rebuilding
      - name: Build processor artifacts
        working-directory: processor
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          source .venv/bin/activate
          
          # Show cache status before build
          echo "=== Build Cache Status ==="
          if [ -f .build_cache.json ]; then
            echo "✅ Build cache found"
            echo "Cache size: $(wc -c < .build_cache.json) bytes"
            echo "Cache modified: $(stat -c %y .build_cache.json 2>/dev/null || stat -f %Sm .build_cache.json)"
          else
            echo "❌ No build cache found - will rebuild everything"
          fi
          
          # Run diagnostics first (if available)
          if [ -f diagnose_cache.py ]; then
            python diagnose_cache.py || true
          fi
          
          # Build with appropriate command
          if [[ "${{ inputs.force_rebuild }}" == "true" ]]; then
            echo "🔨 Force rebuilding all artifacts..."
            python build.py rebuild
          else
            echo "🔄 Running incremental build..."
            python build.py build -v
          fi
          
          # Show what was processed
          echo "=== Build Summary ==="
          python build.py status
      
      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: Deploy ${{ github.sha }}